//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.26 at 03:07:18 ÏÂÎç CST 
//


package com.kedacom.dpss.dtdu.pojo.transport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CommonPicInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonPicInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KedaDevId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GbDevId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Lane" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PicFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PicNum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="BestTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="InTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="OutTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="PicDtlList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element ref="{http://www.kedacom.com/xsd/Kdicp}PicDtl"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonPicInfoType", propOrder = {
    "kedaDevId",
    "gbDevId",
    "lane",
    "picFlag",
    "picNum",
    "bestTime",
    "inTime",
    "outTime",
    "picDtlList"
})
public class CommonPicInfoType {

    @XmlElement(name = "KedaDevId")
    protected String kedaDevId;
    @XmlElement(name = "GbDevId")
    protected String gbDevId;
    @XmlElement(name = "Lane")
    protected int lane;
    @XmlElement(name = "PicFlag", required = true)
    protected String picFlag;
    @XmlElement(name = "PicNum")
    protected int picNum;
    @XmlElement(name = "BestTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar bestTime;
    @XmlElement(name = "InTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar inTime;
    @XmlElement(name = "OutTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar outTime;
    @XmlElement(name = "PicDtlList", required = true)
    protected CommonPicInfoType.PicDtlList picDtlList;

    /**
     * Gets the value of the kedaDevId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKedaDevId() {
        return kedaDevId;
    }

    /**
     * Sets the value of the kedaDevId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKedaDevId(String value) {
        this.kedaDevId = value;
    }

    /**
     * Gets the value of the gbDevId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGbDevId() {
        return gbDevId;
    }

    /**
     * Sets the value of the gbDevId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGbDevId(String value) {
        this.gbDevId = value;
    }

    /**
     * Gets the value of the lane property.
     * 
     */
    public int getLane() {
        return lane;
    }

    /**
     * Sets the value of the lane property.
     * 
     */
    public void setLane(int value) {
        this.lane = value;
    }

    /**
     * Gets the value of the picFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPicFlag() {
        return picFlag;
    }

    /**
     * Sets the value of the picFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPicFlag(String value) {
        this.picFlag = value;
    }

    /**
     * Gets the value of the picNum property.
     * 
     */
    public int getPicNum() {
        return picNum;
    }

    /**
     * Sets the value of the picNum property.
     * 
     */
    public void setPicNum(int value) {
        this.picNum = value;
    }

    /**
     * Gets the value of the bestTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBestTime() {
        return bestTime;
    }

    /**
     * Sets the value of the bestTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBestTime(XMLGregorianCalendar value) {
        this.bestTime = value;
    }

    /**
     * Gets the value of the inTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInTime() {
        return inTime;
    }

    /**
     * Sets the value of the inTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInTime(XMLGregorianCalendar value) {
        this.inTime = value;
    }

    /**
     * Gets the value of the outTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOutTime() {
        return outTime;
    }

    /**
     * Sets the value of the outTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOutTime(XMLGregorianCalendar value) {
        this.outTime = value;
    }

    /**
     * Gets the value of the picDtlList property.
     * 
     * @return
     *     possible object is
     *     {@link CommonPicInfoType.PicDtlList }
     *     
     */
    public CommonPicInfoType.PicDtlList getPicDtlList() {
        return picDtlList;
    }

    /**
     * Sets the value of the picDtlList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonPicInfoType.PicDtlList }
     *     
     */
    public void setPicDtlList(CommonPicInfoType.PicDtlList value) {
        this.picDtlList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element ref="{http://www.kedacom.com/xsd/Kdicp}PicDtl"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "picDtl"
    })
    public static class PicDtlList {

        @XmlElement(name = "PicDtl", namespace = "http://www.kedacom.com/xsd/Kdicp", required = true)
        protected List<PicDtl> picDtl;

        /**
         * Gets the value of the picDtl property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the picDtl property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPicDtl().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PicDtl }
         * 
         * 
         */
        public List<PicDtl> getPicDtl() {
            if (picDtl == null) {
                picDtl = new ArrayList<PicDtl>();
            }
            return this.picDtl;
        }

    }

}
