//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.26 at 03:07:18 ÏÂÎç CST 
//


package com.kedacom.dpss.dtdu.pojo.transport;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kedacom.dpss.dtdu.pojo.transport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kedacom.dpss.dtdu.pojo.transport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonPicInfoType }
     * 
     */
    public PersonPicInfoType createPersonPicInfoType() {
        return new PersonPicInfoType();
    }

    /**
     * Create an instance of {@link CommonPicInfoType }
     * 
     */
    public CommonPicInfoType createCommonPicInfoType() {
        return new CommonPicInfoType();
    }

    /**
     * Create an instance of {@link ObjectPicInfoType }
     * 
     */
    public ObjectPicInfoType createObjectPicInfoType() {
        return new ObjectPicInfoType();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link CommonPicInfoType.PicDtlList }
     * 
     */
    public CommonPicInfoType.PicDtlList createCommonPicInfoTypePicDtlList() {
        return new CommonPicInfoType.PicDtlList();
    }

    /**
     * Create an instance of {@link VehiclePicInfoType }
     * 
     */
    public VehiclePicInfoType createVehiclePicInfoType() {
        return new VehiclePicInfoType();
    }

    /**
     * Create an instance of {@link PicDtl }
     * 
     */
    public PicDtl createPicDtl() {
        return new PicDtl();
    }

}
