//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.26 at 03:07:18 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kedacom.com/xsd/Kdicp")
package com.kedacom.dpss.dtdu.pojo.transport;
