//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.26 at 03:07:18 ÏÂÎç CST 
//


package com.kedacom.dpss.dtdu.pojo.transport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonPicInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonPicInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ComPicInfo" type="{http://www.kedacom.com/xsd/Kdicp}CommonPicInfoType"/>
 *         &lt;element name="Pose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BodySFtr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsDriver" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonPicInfoType", propOrder = {
    "comPicInfo",
    "pose",
    "bodySFtr",
    "isDriver"
})
public class PersonPicInfoType {

    @XmlElement(name = "ComPicInfo", required = true)
    protected CommonPicInfoType comPicInfo;
    @XmlElement(name = "Pose")
    protected String pose;
    @XmlElement(name = "BodySFtr")
    protected String bodySFtr;
    @XmlElement(name = "IsDriver")
    protected Boolean isDriver;

    /**
     * Gets the value of the comPicInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CommonPicInfoType }
     *     
     */
    public CommonPicInfoType getComPicInfo() {
        return comPicInfo;
    }

    /**
     * Sets the value of the comPicInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonPicInfoType }
     *     
     */
    public void setComPicInfo(CommonPicInfoType value) {
        this.comPicInfo = value;
    }

    /**
     * Gets the value of the pose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPose() {
        return pose;
    }

    /**
     * Sets the value of the pose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPose(String value) {
        this.pose = value;
    }

    /**
     * Gets the value of the bodySFtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBodySFtr() {
        return bodySFtr;
    }

    /**
     * Sets the value of the bodySFtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBodySFtr(String value) {
        this.bodySFtr = value;
    }

    /**
     * Gets the value of the isDriver property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDriver() {
        return isDriver;
    }

    /**
     * Sets the value of the isDriver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDriver(Boolean value) {
        this.isDriver = value;
    }

}
