//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.26 at 03:07:18 ÏÂÎç CST 
//


package com.kedacom.dpss.dtdu.pojo.transport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PicInfoType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="person"/>
 *               &lt;enumeration value="vehicle"/>
 *               &lt;enumeration value="object"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;sequence>
 *           &lt;element name="PInfo" type="{http://www.kedacom.com/xsd/Kdicp}PersonPicInfoType" minOccurs="0"/>
 *           &lt;element name="VInfo" type="{http://www.kedacom.com/xsd/Kdicp}VehiclePicInfoType" minOccurs="0"/>
 *           &lt;element name="OInfo" type="{http://www.kedacom.com/xsd/Kdicp}ObjectPicInfoType" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="dsPltType" default="1">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dsType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "picInfoType",
    "pInfo",
    "vInfo",
    "oInfo"
})
@XmlRootElement(name = "Target")
public class Target {

    @XmlElement(name = "PicInfoType", required = true)
    protected String picInfoType;
    @XmlElement(name = "PInfo")
    protected PersonPicInfoType pInfo;
    @XmlElement(name = "VInfo")
    protected VehiclePicInfoType vInfo;
    @XmlElement(name = "OInfo")
    protected ObjectPicInfoType oInfo;
    @XmlAttribute
    protected String dsPltType;
    @XmlAttribute
    protected String dsType;

    /**
     * Gets the value of the picInfoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPicInfoType() {
        return picInfoType;
    }

    /**
     * Sets the value of the picInfoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPicInfoType(String value) {
        this.picInfoType = value;
    }

    /**
     * Gets the value of the pInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PersonPicInfoType }
     *     
     */
    public PersonPicInfoType getPInfo() {
        return pInfo;
    }

    /**
     * Sets the value of the pInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonPicInfoType }
     *     
     */
    public void setPInfo(PersonPicInfoType value) {
        this.pInfo = value;
    }

    /**
     * Gets the value of the vInfo property.
     * 
     * @return
     *     possible object is
     *     {@link VehiclePicInfoType }
     *     
     */
    public VehiclePicInfoType getVInfo() {
        return vInfo;
    }

    /**
     * Sets the value of the vInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehiclePicInfoType }
     *     
     */
    public void setVInfo(VehiclePicInfoType value) {
        this.vInfo = value;
    }

    /**
     * Gets the value of the oInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectPicInfoType }
     *     
     */
    public ObjectPicInfoType getOInfo() {
        return oInfo;
    }

    /**
     * Sets the value of the oInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectPicInfoType }
     *     
     */
    public void setOInfo(ObjectPicInfoType value) {
        this.oInfo = value;
    }

    /**
     * Gets the value of the dsPltType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsPltType() {
        if (dsPltType == null) {
            return "1";
        } else {
            return dsPltType;
        }
    }

    /**
     * Sets the value of the dsPltType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsPltType(String value) {
        this.dsPltType = value;
    }

    /**
     * Gets the value of the dsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsType() {
        return dsType;
    }

    /**
     * Sets the value of the dsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsType(String value) {
        this.dsType = value;
    }

}
