//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.26 at 03:07:18 ÏÂÎç CST 
//


package com.kedacom.dpss.dtdu.pojo.transport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehiclePicInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehiclePicInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ComPicInfo" type="{http://www.kedacom.com/xsd/Kdicp}CommonPicInfoType"/>
 *         &lt;element name="IfHavePlt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PltType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PltCol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PltNum" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PltGNum" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsPltAlt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsPltBlc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Speed" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SpdLmt" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Brand" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Style" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VLength" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="VWidth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="VHeight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="VCol" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TrafficOffence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehiclePicInfoType", propOrder = {
    "comPicInfo",
    "ifHavePlt",
    "pltType",
    "pltCol",
    "pltNum",
    "pltGNum",
    "isPltAlt",
    "isPltBlc",
    "speed",
    "spdLmt",
    "status",
    "brand",
    "style",
    "vLength",
    "vWidth",
    "vHeight",
    "vCol",
    "trafficOffence"
})
public class VehiclePicInfoType {

    @XmlElement(name = "ComPicInfo", required = true)
    protected CommonPicInfoType comPicInfo;
    @XmlElement(name = "IfHavePlt")
    protected Boolean ifHavePlt;
    @XmlElement(name = "PltType")
    protected String pltType;
    @XmlElement(name = "PltCol")
    protected String pltCol;
    @XmlElement(name = "PltNum")
    protected String pltNum;
    @XmlElement(name = "PltGNum")
    protected String pltGNum;
    @XmlElement(name = "IsPltAlt")
    protected Boolean isPltAlt;
    @XmlElement(name = "IsPltBlc")
    protected Boolean isPltBlc;
    @XmlElement(name = "Speed")
    protected Integer speed;
    @XmlElement(name = "SpdLmt")
    protected Integer spdLmt;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "Brand")
    protected String brand;
    @XmlElement(name = "Style")
    protected String style;
    @XmlElement(name = "VLength")
    protected Integer vLength;
    @XmlElement(name = "VWidth")
    protected Integer vWidth;
    @XmlElement(name = "VHeight")
    protected Integer vHeight;
    @XmlElement(name = "VCol")
    protected String vCol;
    @XmlElement(name = "TrafficOffence")
    protected String trafficOffence;

    /**
     * Gets the value of the comPicInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CommonPicInfoType }
     *     
     */
    public CommonPicInfoType getComPicInfo() {
        return comPicInfo;
    }

    /**
     * Sets the value of the comPicInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonPicInfoType }
     *     
     */
    public void setComPicInfo(CommonPicInfoType value) {
        this.comPicInfo = value;
    }

    /**
     * Gets the value of the ifHavePlt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIfHavePlt() {
        return ifHavePlt;
    }

    /**
     * Sets the value of the ifHavePlt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIfHavePlt(Boolean value) {
        this.ifHavePlt = value;
    }

    /**
     * Gets the value of the pltType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPltType() {
        return pltType;
    }

    /**
     * Sets the value of the pltType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPltType(String value) {
        this.pltType = value;
    }

    /**
     * Gets the value of the pltCol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPltCol() {
        return pltCol;
    }

    /**
     * Sets the value of the pltCol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPltCol(String value) {
        this.pltCol = value;
    }

    /**
     * Gets the value of the pltNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPltNum() {
        return pltNum;
    }

    /**
     * Sets the value of the pltNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPltNum(String value) {
        this.pltNum = value;
    }

    /**
     * Gets the value of the pltGNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPltGNum() {
        return pltGNum;
    }

    /**
     * Sets the value of the pltGNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPltGNum(String value) {
        this.pltGNum = value;
    }

    /**
     * Gets the value of the isPltAlt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPltAlt() {
        return isPltAlt;
    }

    /**
     * Sets the value of the isPltAlt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPltAlt(Boolean value) {
        this.isPltAlt = value;
    }

    /**
     * Gets the value of the isPltBlc property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPltBlc() {
        return isPltBlc;
    }

    /**
     * Sets the value of the isPltBlc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPltBlc(Boolean value) {
        this.isPltBlc = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSpeed(Integer value) {
        this.speed = value;
    }

    /**
     * Gets the value of the spdLmt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSpdLmt() {
        return spdLmt;
    }

    /**
     * Sets the value of the spdLmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSpdLmt(Integer value) {
        this.spdLmt = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the vLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVLength() {
        return vLength;
    }

    /**
     * Sets the value of the vLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVLength(Integer value) {
        this.vLength = value;
    }

    /**
     * Gets the value of the vWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVWidth() {
        return vWidth;
    }

    /**
     * Sets the value of the vWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVWidth(Integer value) {
        this.vWidth = value;
    }

    /**
     * Gets the value of the vHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVHeight() {
        return vHeight;
    }

    /**
     * Sets the value of the vHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVHeight(Integer value) {
        this.vHeight = value;
    }

    /**
     * Gets the value of the vCol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVCol() {
        return vCol;
    }

    /**
     * Sets the value of the vCol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVCol(String value) {
        this.vCol = value;
    }

    /**
     * Gets the value of the trafficOffence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrafficOffence() {
        return trafficOffence;
    }

    /**
     * Sets the value of the trafficOffence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrafficOffence(String value) {
        this.trafficOffence = value;
    }

}
